### ISSUE TITLE
TypeError: attribute name must be string, not 'bytes'

### ISSUE THREAD

**Issue by olesure1** [fsinfuhh/Bitpoll#27]
Hi, 
I'm trying to implement and start your project on my Win10, python 3.6.
When trying to migrate the manage.py, the error 

> "TypeError: attribute name must be string, not 'bytes'" 

pops up, with multiple files and lines in reference. The last one is 

> .pyenv\lib\site-packages\django\db\models\fields\related.py", line 744, in contribute_to_related_class
    setattr(cls._meta.concrete_model, related.get_accessor_name(), self.related_accessor_class(related))

As I do not have much knowledge about python and coding in general, I don't know whether this matters or not - when starting the server without migrating, the error when opening the page is

> "django.template.exceptions.TemplateSyntaxError: 'raven' is not a registered tag library. Must be one of: [...] "

Thanks and regards

**Comment by Akasch** [comment]
the first error is fixed now, seems like nobody have run the initial migrations for a long time.

The second error is due to the missing migrations. I have it on my todo list to generate a better error page.

**Comment by olesure1** [comment]
Hi @Akasch, 
thanks for the quick reply and fixing the migration error.
Unfortunately this does not resolve my second error. 
As attached in first image, I re-migrated after having the changes implemented (makemigrations, migrate). When starting the server and visiting the page, error occurs again (see code below image).


Thanks and regards

![image](https://user-images.githubusercontent.com/40198289/41364066-d0db8f6c-6f35-11e8-88d0-6704b41d6bbe.png)

`Traceback (most recent call last):
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\template\defaulttags.py", line 1025, in find_library
    return parser.libraries[name]
KeyError: 'raven'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\schur\AppData\Local\Continuum\anaconda3\Lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\core\handlers\wsgi.py", line 146, in __call__
    response = self.get_response(request)
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\core\handlers\base.py", line 81, in get_response
    response = self._middleware_chain(request)
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\core\handlers\exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\core\handlers\exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\core\handlers\exception.py", line 126, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\bitpoll\urls.py", line 62, in handler500
    return render(request, '500.html', status=500)
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\template\loaders\cached.py", line 55, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\template\loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\template\defaulttags.py", line 1082, in load
    lib = find_library(parser, name)
  File "C:\Users\schur\Downloads\Bitpoll\Bitpoll-master\.pyenv\lib\site-packages\django\template\defaulttags.py", line 1029, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'raven' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
comment_permissions
csp
django_markdown
django_markdown_static
group_tags
humanize
i18n
l10n
log
pipeline
poll_filter
poll_permissions
poll_voted
poll_watched
settings_value
static
staticfiles
tz
userformat
vote_permissions
widget_tweaks
[13/Jun/2018 18:14:45] "GET / HTTP/1.1" 500 59`

**Comment by Akasch** [comment]
This is the broken error Page. If you set DEBUG=True in the settings_local.py a detailed error page should show up. I will try to fix the Production error page tomorrow.
